-- CB5: Add AI-generated tags array to Item
-- Tracks search tags generated by Google Vision + Claude Haiku pipeline.
-- Missing from Neon production — was added to schema without a migration file.

ALTER TABLE "Item" ADD COLUMN IF NOT EXISTS "tags" TEXT[] NOT NULL DEFAULT '{}';
