ALTER TABLE "Sale" ADD COLUMN "purchaseModel" TEXT NOT NULL DEFAULT 'SUBSCRIPTION';
ALTER TABLE "Sale" ADD COLUMN "alaCarte" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Sale" ADD COLUMN "alaCarteFeePaid" BOOLEAN NOT NULL DEFAULT false;
