/**
 * Coupon Controller — Sprint 3: Shopper Loyalty Program
 *
 * Issues $5 fixed coupons after each completed purchase.
 * Shoppers can view and redeem coupons at checkout.
 */

import crypto from 'crypto';
import { Response } from 'express';
import { Resend } from 'resend';
import { AuthRequest } from '../middleware/auth';
import { prisma } from '../lib/prisma';
import { spendXp, XP_SINKS } from '../services/xpService';
import { buildEmail } from '../services/emailTemplateService';

let _resend: any = null;
const getResendClient = () => {
  if (!_resend && process.env.RESEND_API_KEY) {
    try { _resend = new Resend(process.env.RESEND_API_KEY); } catch { _resend = null; }
  }
  return _resend;
};

/** Generate an 8-char uppercase hex code, e.g. "A3F2C891" */
function generateCouponCode(): string {
  return crypto.randomBytes(4).toString('hex').toUpperCase();
}

// ---------------------------------------------------------------------------
// GET /api/coupons — list authenticated user's active, non-expired coupons
// ---------------------------------------------------------------------------
export const getUserCoupons = async (req: AuthRequest, res: Response) => {
  if (!req.user) return res.status(401).json({ message: 'Authentication required' });

  try {
    const coupons = await prisma.coupon.findMany({
      where: {
        userId: req.user.id,
        status: 'ACTIVE',
        expiresAt: { gt: new Date() },
      },
      orderBy: { expiresAt: 'asc' },
      select: {
        id: true,
        code: true,
        discountType: true,
        discountValue: true,
        minPurchaseAmount: true,
        expiresAt: true,
        status: true,
        createdAt: true,
      },
    });

    res.json({ coupons });
  } catch (err) {
    console.error('[coupon] getUserCoupons error:', err);
    res.status(500).json({ message: 'Failed to load coupons' });
  }
};

// ---------------------------------------------------------------------------
// POST /api/coupons/validate — preview discount for a code + purchase amount
// ---------------------------------------------------------------------------
export const validateCoupon = async (req: AuthRequest, res: Response) => {
  if (!req.user) return res.status(401).json({ message: 'Authentication required' });

  const { code, amount } = req.body as { code: string; amount: number };

  if (!code) return res.status(400).json({ valid: false, message: 'Coupon code is required' });

  try {
    const coupon = await prisma.coupon.findUnique({ where: { code: code.trim().toUpperCase() } });

    if (!coupon) {
      return res.json({ valid: false, message: 'Coupon not found' });
    }
    // NOTE: No userId ownership check — XP-sink coupons are generated by organizers
    // and given to shoppers. Any authenticated user with a valid code can redeem it.
    if (coupon.status !== 'ACTIVE') {
      return res.json({ valid: false, message: 'This coupon has already been used' });
    }
    if (coupon.expiresAt < new Date()) {
      return res.json({ valid: false, message: 'This coupon has expired' });
    }
    if (coupon.minPurchaseAmount && amount > 0 && amount < coupon.minPurchaseAmount) {
      return res.json({
        valid: false,
        message: `Minimum purchase of $${coupon.minPurchaseAmount.toFixed(2)} required`,
      });
    }

    // Calculate discount
    let discount = 0;
    if (coupon.discountType === 'FIXED') {
      discount = coupon.discountValue;
    } else {
      discount = amount > 0 ? (amount * coupon.discountValue) / 100 : coupon.discountValue;
      if (coupon.maxDiscountAmount) {
        discount = Math.min(discount, coupon.maxDiscountAmount);
      }
    }

    const finalAmount = amount > 0 ? Math.max(amount - discount, 0.5) : amount;

    res.json({
      valid: true,
      discount: parseFloat(discount.toFixed(2)),
      finalAmount: parseFloat(finalAmount.toFixed(2)),
      couponId: coupon.id,
    });
  } catch (err) {
    console.error('[coupon] validateCoupon error:', err);
    res.status(500).json({ valid: false, message: 'Failed to validate coupon' });
  }
};

// ---------------------------------------------------------------------------
// issueLoyaltyCoupon — DISABLED S404
// Not in Explorer's Guild spec. Created undisclosed organizer payout liability:
// every $5 redemption silently reduced the organizer's Stripe transfer by $5.
// XP rewards (purchase XP, rank perks) replace shopper retention.
// Stub kept here to satisfy stripeController import without a refactor.
// ---------------------------------------------------------------------------
export const issueLoyaltyCoupon = async (
  _userId: string,
  _sourcePurchaseId: string,
): Promise<void> => {
  // No-op — see comment above.
};

// ---------------------------------------------------------------------------
// POST /api/coupons/generate — organizer XP sink: spend 50 XP → $1-off coupon
//
// Spec (Explorer's Guild master spec, S404):
//   Cost: 50 XP (or $1.99 a la carte — handled separately by billing)
//   Output: $1 FIXED coupon, single-use, 30-day expiry
//   Cap: max 5 generated per organizer per calendar month
//   Financial model: organizer absorbs the $1 discount from their Stripe payout
//   Redemption: any authenticated shopper can enter the code at checkout
// ---------------------------------------------------------------------------
export const generateXpSinkCoupon = async (req: AuthRequest, res: Response) => {
  if (!req.user) return res.status(401).json({ message: 'Authentication required' });

  const organizerId = req.user.id;

  try {
    // Enforce 5/month cap — count this organizer's XP-sink coupons this calendar month
    const monthStart = new Date();
    monthStart.setDate(1);
    monthStart.setHours(0, 0, 0, 0);

    const thisMonthCount = await prisma.coupon.count({
      where: {
        userId: organizerId,
        sourcePurchaseId: null, // XP-sink coupons have no sourcePurchaseId; loyalty coupons do
        createdAt: { gte: monthStart },
      },
    });

    if (thisMonthCount >= 5) {
      return res.status(429).json({
        message: 'Monthly limit reached — you can generate up to 5 coupons per month.',
        generated: thisMonthCount,
        limit: 5,
      });
    }

    // Spend 50 XP — spendXp returns false if insufficient balance or below rank floor
    const spent = await spendXp(organizerId, XP_SINKS.COUPON_GENERATE, 'COUPON_GENERATE', {
      description: 'Generated $1-off shopper coupon',
    });

    if (!spent) {
      return res.status(400).json({
        message: `Not enough XP. Coupon generation costs ${XP_SINKS.COUPON_GENERATE} XP.`,
      });
    }

    // Generate unique code — retry up to 3 times on collision
    let code = '';
    let existing = null;
    for (let attempt = 0; attempt < 3; attempt++) {
      code = generateCouponCode();
      existing = await prisma.coupon.findUnique({ where: { code } });
      if (!existing) break;
    }
    if (existing) {
      console.error('[coupon] Failed to generate unique XP sink coupon code after 3 attempts');
      return res.status(500).json({ message: 'Failed to generate coupon code — please try again' });
    }

    const expiresAt = new Date();
    expiresAt.setDate(expiresAt.getDate() + 30);

    const coupon = await prisma.coupon.create({
      data: {
        code,
        userId: organizerId,      // tracks who generated it (for the 5/month cap)
        discountType: 'FIXED',
        discountValue: 1.00,
        status: 'ACTIVE',
        sourcePurchaseId: null,   // null = XP-sink coupon (not a loyalty award)
        expiresAt,
      },
      select: {
        code: true,
        discountValue: true,
        expiresAt: true,
        status: true,
      },
    });

    res.json({
      code: coupon.code,
      discountValue: coupon.discountValue,
      expiresAt: coupon.expiresAt,
      xpSpent: XP_SINKS.COUPON_GENERATE,
      generatedThisMonth: thisMonthCount + 1,
      monthlyLimit: 5,
      message: `Coupon created! Share code ${coupon.code} with a shopper. They apply it at checkout for $1 off. The discount comes out of your payout.`,
    });
  } catch (err) {
    console.error('[coupon] generateXpSinkCoupon error:', err);
    res.status(500).json({ message: 'Failed to generate coupon' });
  }
};

// ---------------------------------------------------------------------------
// markCouponUsed — called from stripeController after payment_intent.succeeded
// Fire-and-forget: caller must .catch() this
// ---------------------------------------------------------------------------
export const markCouponUsed = async (
  couponId: string,
  redeemedPurchaseId: string,
): Promise<void> => {
  await prisma.coupon.update({
    where: { id: couponId },
    data: {
      status: 'USED',
      usedAt: new Date(),
      redeemedPurchaseId,
    },
  });
};
