ALTER TABLE "Sale" ADD COLUMN IF NOT EXISTS "attendanceCount" INTEGER;
ALTER TABLE "Sale" ADD COLUMN IF NOT EXISTS "buyersPremiumPct" DECIMAL(5,2);
ALTER TABLE "Item" ADD COLUMN IF NOT EXISTS "lotNumber" TEXT;
