-- No-op (2026-07-30): this migration duplicated OrganizerClaimEmail table creation.
--
-- Confirmed via `prisma migrate status` against production (Railway): the table this
-- migration creates was ALREADY created by 20260223014341_organizer_claim_email
-- (renamed 2026-07-30 from 20250501080000_organizer_claim_email, which production's
-- own _prisma_migrations bookkeeping confirms was applied under that original name --
-- see claude_docs/STATE.md's Row 19 for the full investigation). That migration sorts
-- earlier than this one and creates the same table, columns, indexes, and foreign key.
--
-- This migration's NAME is left completely unchanged -- production's _prisma_migrations
-- table already has it recorded as applied under this exact name, and renaming or
-- deleting the folder would desync that bookkeeping for no benefit (production never
-- re-runs an already-applied migration's SQL against a live database; only a
-- from-scratch shadow-database build, e.g. `prisma migrate dev`, replays this file).
--
-- Only the SQL BODY is emptied, so a fresh shadow-database build no longer tries to
-- CREATE TABLE "OrganizerClaimEmail" a second time and fail with P3006 ("already
-- exists"). This is the only thing that was ever wrong with this migration file --
-- it never needs to run its original SQL again anywhere.
