import React, { useState, useEffect } from 'react';
import { useRouter } from 'next/router';
import { useAuth } from '../../components/AuthContext';
import api from '../../lib/api';
import { BookOpen, CheckCircle, Trash2, Play } from 'lucide-react';

interface EncyclopediaEntry {
  id: string;
  slug: string;
  title: string;
  category: string;
  content: string;
  triggerItemId?: string;
  createdAt: string;
  status: string;
}

interface CuratorStatus {
  autoGeneratedCount: number;
  publishedCount: number;
  enrichedButFlaggedCount: number;
  totalEncyclopediaEntries: number;
}

const AdminEncyclopedia = () => {
  const router = useRouter();
  const { user, isLoading } = useAuth();
  const [entries, setEntries] = useState<EncyclopediaEntry[]>([]);
  const [curatorStatus, setCuratorStatus] = useState<CuratorStatus | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [processingEntryId, setProcessingEntryId] = useState<string | null>(null);
  const [runningFullPass, setRunningFullPass] = useState(false);
  const [deleteConfirm, setDeleteConfirm] = useState<string | null>(null);

  useEffect(() => {
    if (!isLoading && (!user || !user.roles?.includes('ADMIN'))) {
      router.push('/');
    }
  }, [user, isLoading, router]);

  const fetchEntries = async () => {
    try {
      setLoading(true);
      const res = await api.get('/admin/curator/entries');
      setEntries(res.data.entries || []);
    } catch (err) {
      console.error('Error fetching encyclopedia entries:', err);
      setError('Failed to load encyclopedia entries');
    } finally {
      setLoading(false);
    }
  };

  const fetchCuratorStatus = async () => {
    try {
      const res = await api.get('/admin/curator/status');
      setCuratorStatus(res.data);
    } catch (err) {
      console.error('Error fetching curator status:', err);
    }
  };

  useEffect(() => {
    if (user?.roles?.includes('ADMIN')) {
      fetchEntries();
      fetchCuratorStatus();
    }
  }, [user]);

  const handlePromote = async (entryId: string) => {
    try {
      setProcessingEntryId(entryId);
      await api.post(`/admin/curator/run/${entryId}`);
      setError('');
      // Refresh entries list
      await fetchEntries();
      await fetchCuratorStatus();
    } catch (err) {
      console.error('Error promoting entry:', err);
      setError('Failed to promote entry');
    } finally {
      setProcessingEntryId(null);
    }
  };

  const handleReject = async (entryId: string) => {
    try {
      setProcessingEntryId(entryId);
      // Call PATCH endpoint to mark as REJECTED
      await api.patch(`/admin/curator/entries/${entryId}`, { status: 'REJECTED' });
      setError('');
      setDeleteConfirm(null);
      // Refresh entries list
      await fetchEntries();
      await fetchCuratorStatus();
    } catch (err) {
      console.error('Error rejecting entry:', err);
      setError('Failed to reject entry');
    } finally {
      setProcessingEntryId(null);
    }
  };

  const handleRunFullPass = async () => {
    try {
      setRunningFullPass(true);
      await api.post('/admin/curator/run');
      setError('');
      // Refresh data after running full pass
      await fetchEntries();
      await fetchCuratorStatus();
    } catch (err) {
      console.error('Error running full curator pass:', err);
      setError('Failed to run curator pass');
    } finally {
      setRunningFullPass(false);
    }
  };

  const getPreview = (content: string) => {
    return content.substring(0, 200).replace(/[#*_`]/g, '').trim() + (content.length > 200 ? '...' : '');
  };

  if (isLoading || loading) {
    return (
      <div className="container mx-auto px-4 py-8">
        <div className="text-center text-warm-600 dark:text-warm-400">Loading encyclopedia curator...</div>
      </div>
    );
  }

  if (!user || !user.roles?.includes('ADMIN')) {
    return null;
  }

  return (
    <div className="container mx-auto px-4 py-8">
      {/* Header */}
      <div className="mb-8">
        <div className="flex items-center gap-2 mb-2">
          <BookOpen size={32} className="text-blue-600 dark:text-blue-400" />
          <h1 className="text-3xl font-bold text-warm-900 dark:text-warm-100">Encyclopedia Curator</h1>
        </div>
        <p className="text-warm-600 dark:text-warm-400">Review and promote auto-generated encyclopedia entries</p>
      </div>

      {/* Error message */}
      {error && (
        <div className="bg-red-100 border border-red-400 text-red-700 dark:text-red-300 dark:bg-red-900/30 dark:border-red-700 px-4 py-3 rounded mb-6">
          {error}
        </div>
      )}

      {/* Curator Status Cards */}
      {curatorStatus && (
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-8">
          <div className="bg-white dark:bg-gray-800 rounded-lg p-6 shadow">
            <p className="text-warm-600 dark:text-warm-400 text-sm font-medium mb-2">Awaiting Review</p>
            <p className="text-3xl font-bold text-warm-900 dark:text-warm-100">{curatorStatus.autoGeneratedCount}</p>
          </div>
          <div className="bg-white dark:bg-gray-800 rounded-lg p-6 shadow">
            <p className="text-warm-600 dark:text-warm-400 text-sm font-medium mb-2">Published</p>
            <p className="text-3xl font-bold text-green-600 dark:text-green-400">{curatorStatus.publishedCount}</p>
          </div>
          <div className="bg-white dark:bg-gray-800 rounded-lg p-6 shadow">
            <p className="text-warm-600 dark:text-warm-400 text-sm font-medium mb-2">Enriched (Pending)</p>
            <p className="text-3xl font-bold text-amber-600 dark:text-amber-400">{curatorStatus.enrichedButFlaggedCount}</p>
          </div>
          <div className="bg-white dark:bg-gray-800 rounded-lg p-6 shadow">
            <p className="text-warm-600 dark:text-warm-400 text-sm font-medium mb-2">Total Entries</p>
            <p className="text-3xl font-bold text-blue-600 dark:text-blue-400">{curatorStatus.totalEncyclopediaEntries}</p>
          </div>
        </div>
      )}

      {/* Run Full Pass Button */}
      <div className="mb-8">
        <button
          onClick={handleRunFullPass}
          disabled={runningFullPass}
          className="inline-flex items-center gap-2 px-6 py-3 bg-blue-600 hover:bg-blue-700 disabled:bg-blue-400 disabled:cursor-not-allowed text-white rounded-lg font-medium transition"
        >
          <Play size={16} />
          {runningFullPass ? 'Running Curator Pass...' : 'Run Full Curator Pass'}
        </button>
      </div>

      {/* Entries List */}
      <div className="bg-white dark:bg-gray-800 shadow rounded-lg overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full table-fixed">
            <thead className="bg-warm-50 dark:bg-gray-900 border-b border-warm-200 dark:border-gray-700">
              <tr>
                <th className="w-[22%] px-6 py-3 text-left text-sm font-medium text-warm-900 dark:text-warm-100">Title</th>
                <th className="w-[16%] px-6 py-3 text-left text-sm font-medium text-warm-900 dark:text-warm-100">Category</th>
                <th className="w-[14%] px-6 py-3 text-left text-sm font-medium text-warm-900 dark:text-warm-100">Triggered By</th>
                <th className="w-[12%] px-6 py-3 text-left text-sm font-medium text-warm-900 dark:text-warm-100">Created</th>
                <th className="w-[20%] px-6 py-3 text-left text-sm font-medium text-warm-900 dark:text-warm-100">Preview</th>
                <th className="w-[16%] px-6 py-3 text-center text-sm font-medium text-warm-900 dark:text-warm-100">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-warm-200 dark:divide-gray-700">
              {entries.map(entry => (
                <tr key={entry.id} className="hover:bg-warm-50 dark:hover:bg-gray-700">
                  <td className="px-6 py-4 text-sm font-medium text-warm-900 dark:text-warm-100 max-w-xs truncate">
                    {entry.title}
                  </td>
                  <td className="px-6 py-4 text-sm text-warm-600 dark:text-warm-400">
                    <span className="inline-block px-2 py-1 bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300 rounded text-xs">
                      {entry.category}
                    </span>
                  </td>
                  <td className="px-6 py-4 text-sm text-warm-600 dark:text-warm-400">
                    {entry.triggerItemId ? (
                      <a href={`/organizer/items/${entry.triggerItemId}`} className="text-blue-600 dark:text-blue-400 hover:underline">
                        Item #{entry.triggerItemId.substring(0, 8)}
                      </a>
                    ) : (
                      <span className="text-gray-400">—</span>
                    )}
                  </td>
                  <td className="px-6 py-4 text-sm text-warm-600 dark:text-warm-400">
                    {new Date(entry.createdAt).toLocaleDateString()}
                  </td>
                  <td className="px-6 py-4 text-sm text-warm-600 dark:text-warm-400 max-w-sm truncate">
                    {getPreview(entry.content)}
                  </td>
                  <td className="px-6 py-4 text-sm text-center whitespace-nowrap">
                    <div className="flex gap-2 justify-center">
                      <button
                        onClick={() => handlePromote(entry.id)}
                        disabled={processingEntryId === entry.id}
                        className="inline-flex items-center gap-1 px-3 py-1 bg-green-600 hover:bg-green-700 disabled:bg-green-400 disabled:cursor-not-allowed text-white text-xs rounded transition"
                        title="Promote to Published"
                      >
                        <CheckCircle size={14} />
                        Promote
                      </button>
                      <button
                        onClick={() => setDeleteConfirm(entry.id)}
                        disabled={processingEntryId === entry.id || deleteConfirm === entry.id}
                        className="inline-flex items-center gap-1 px-3 py-1 bg-red-600 hover:bg-red-700 disabled:bg-red-400 disabled:cursor-not-allowed text-white text-xs rounded transition"
                        title="Reject / Delete"
                      >
                        <Trash2 size={14} />
                        Reject
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {entries.length === 0 && (
          <div className="text-center py-8">
            <p className="text-warm-600 dark:text-gray-400">No auto-generated encyclopedia entries awaiting review.</p>
          </div>
        )}
      </div>

      {/* Rejection Confirmation Modal */}
      {deleteConfirm && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white dark:bg-gray-800 rounded-lg p-6 max-w-sm">
            <h3 className="text-lg font-bold text-warm-900 dark:text-warm-100 mb-4">Reject Entry?</h3>
            <p className="text-warm-600 dark:text-warm-400 mb-6">
              Are you sure you want to reject this encyclopedia entry? This action cannot be undone.
            </p>
            <div className="flex gap-3 justify-end">
              <button
                onClick={() => setDeleteConfirm(null)}
                className="px-4 py-2 border border-warm-300 dark:border-gray-600 rounded-md text-warm-900 dark:text-warm-100 hover:bg-warm-50 dark:hover:bg-gray-700 transition"
              >
                Cancel
              </button>
              <button
                onClick={() => handleReject(deleteConfirm)}
                className="px-4 py-2 bg-red-600 text-white rounded-md hover:bg-red-700 transition"
              >
                Reject
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default AdminEncyclopedia;
